#########################################################
# Makefile for PSUADE Python directory
#########################################################

SHELL = /bin/sh

clean:
	@rm -f _psuade.so

